oro_menu_config:
    items:
        acme_enrich_color:
            label:              'pim_custom_entity.reference_data.color.menu_entry'
            route:              'pim_customentity_index'
            routeParameters:    { customEntityName: color }
        acme_enrich_brand:
            label:              'pim_custom_entity.reference_data.brand.menu_entry'
            route:              'pim_customentity_index'
            routeParameters:    { customEntityName: brand }
            aclResourceId:      acme_enrich_brand_index
        acme_enrich_fabric:
            label:              'pim_custom_entity.reference_data.fabric.menu_entry'
            route:              'pim_customentity_index'
            routeParameters:    { customEntityName: fabric }
        acme_enrich_pictogram:
            label:              'pim_custom_entity.reference_data.pictogram.menu_entry'
            route:              'pim_customentity_index'
            routeParameters:    { customEntityName: pictogram }
    tree:
        application_menu:
            children:
                pim_reference_data_tab:
                    children:
                        acme_enrich_color: ~
                        acme_enrich_brand: ~
                        acme_enrich_fabric: ~
                        acme_enrich_pictogram: ~
