parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: custom_entity
    database_user: root
    database_password: root
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: '2016-09-01T17:12:01+00:00'
