datagrid:
    brand:
        options:
            entityHint: brand
        source:
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Brand
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            created:
                label: Created
                frontend_type: date
            updated:
                label: Updated
                frontend_type: date
        properties:
            id: ~
            show_link:
                type: url
                route: pim_customentity_show
                params:
                    - id
                    - customEntityName
            edit_link:
                type: url
                route: pim_customentity_edit
                acl_resource: acme_enrich_brand_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_delete
                params:
                    - id
                    - customEntityName
        actions:
            show:
                type:      navigate
                label:     brand.this.show
                icon:      eye-open
                link:      show_link
            edit:
                type:      navigate
                label:     brand.this.edit
                acl_resource: acme_enrich_brand_edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: brand.this.delete
                icon:  trash
                link:  delete_link
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                created:
                    type:             date
                    label:            Created
                    data_name:        rd.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        rd.udapted
                    filter_by_having: true
        sorters:
            columns:
                code:
                    data_name: rd.code
                created:
                    data_name: rd.created
                updated:
                    data_name: rd.udapted
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        mass_actions:
            delete:
                type: delete
                label: pim.grid.mass_action.delete
                entity_name: brand
                acl_resource: ~
                handler: mass_delete
                messages:
                    confirm_title: pim_datagrid.mass_action.delete.confirm_title
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: pim_datagrid.mass_action.delete.confirm_ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    icon: trash

            quick_export_csv:
                type: export
                label: pim.grid.mass_action.quick_export.csv_all
                icon: download
                handler: quick_export
                route: pim_customentity_quickexport
                route_parameters:
                    customEntityName: brand
                    _format: csv
                    _contentType: text/csv
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection

            mass_edit:
                type: redirect
                label: Mass Edit
                icon: edit
                handler: custom_mass_edit
                route: pim_customentity_massedit
                route_parameters:
                    customEntityName: brand
