datagrid:
    color:
        options:
            entityHint: color
        source:
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Color
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            name:
                label: name
            created:
                label: Created
                frontend_type: date
            updated:
                label: Updated
                frontend_type: date
        properties:
            id: ~
            show_link:
                type: url
                route: pim_customentity_show
                params:
                    - id
                    - customEntityName
            edit_link:
                type: url
                route: pim_customentity_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_delete
                params:
                    - id
                    - customEntityName
        actions:
            show:
                type:      navigate
                label:     Show the reference data
                icon:      eye-open
                link:      show_link
            edit:
                type:      navigate
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                name:
                    type:      string
                    label:     Name
                    data_name: rd.name
                created:
                    type:             date
                    label:            Created
                    data_name:        rd.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        rd.udapted
                    filter_by_having: true
        sorters:
            columns:
                code:
                    data_name: rd.code
                name:
                    data_name: rd.name
                created:
                    data_name: rd.created
                updated:
                    data_name: rd.udapted
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
