datagrid:
    color:
        options:
            entityHint: color
        source:
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Color
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            name:
                label: name
            created:
                label: Created
                frontend_type: date
            updated:
                label: Updated
                frontend_type: date
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: o.code
                name:
                    type:      string
                    label:     Name
                    data_name: o.name
                created:
                    type:             date
                    label:            Created
                    data_name:        o.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        o.udapted
                    filter_by_having: true
        sorters:
            columns:
                code:
                    data_name: o.code
                name:
                    data_name: o.name
                created:
                    data_name: o.created
                updated:
                    data_name: o.udapted
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
